# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastro',
            fields=[
                ('nombreLocal', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=60)),
                ('fechaAlta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
