# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20170316_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Local')),
            ],
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('nombreSitio', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=60)),
                ('fechaAlta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
