# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='comentario',
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='valoracion',
            field=models.IntegerField(),
        ),
    ]
