# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20170413_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nombreLocal',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
